export const LEGAL_VERSION = '2026-08-01';

export type LegalBlock = { type: 'p'; text: string } | { type: 'ul'; items: string[] };

export type LegalDoc = {
  slug: string;
  title: string;
  summary: string;
  blocks: LegalBlock[];
};

const V = LEGAL_VERSION;

export const LEGAL_DOCS: LegalDoc[] = [
  {
    slug: 'terminos',
    title: 'Términos del Servicio',
    summary: 'Condiciones de uso de SyncVete para clínicas veterinarias.',
    blocks: [
      { type: 'p', text: `Versión ${V} — República Argentina.` },
      { type: 'p', text: '1. Aceptación. Estos Términos regulan el acceso y uso de SyncVete. Al crear una cuenta o usar la plataforma, el usuario declara haber leído y aceptado estos términos, la Política de Privacidad y la Política de Seguridad. Si actúa en nombre de una clínica o institución, declara tener facultades suficientes para aceptar en su nombre.' },
      { type: 'p', text: '2. Definiciones. SyncVete es la plataforma de gestión veterinaria. Proveedor es el titular y desarrollador. Usuario es el profesional, clínica o persona autorizada. Paciente es el animal cuyos datos registra el usuario. Tutor o propietario es la persona humana vinculada al paciente. Datos clínicos es la información veterinaria, administrativa o personal ingresada en SyncVete.' },
      { type: 'p', text: '3. Objeto. SyncVete ofrece herramientas para administrar clínicas veterinarias, entre otras: agenda, turnos, historia clínica, fichas de pacientes y tutores, evoluciones, imágenes, internación, vacunación, cirugías, laboratorio, inventario, farmacia, facturación, caja, reportes, WhatsApp, recordatorios, portal del tutor e IA clínica, según el plan contratado. Es una herramienta de apoyo y no reemplaza el criterio del veterinario ni la relación con el tutor.' },
      { type: 'p', text: '4. Registro. Para ciertas funciones hace falta una cuenta. El usuario se compromete a dar información veraz, guardar la confidencialidad de sus credenciales, no compartir la contraseña y usar la plataforma solo con fines lícitos. Es responsable de toda actividad hecha desde su cuenta.' },
      { type: 'p', text: '5. Responsabilidades del usuario. El usuario es exclusivamente responsable de la veracidad de lo cargado, del cumplimiento legal, de obtener consentimientos cuando correspondan, del secreto profesional, de mantener actualizada la historia clínica, de la confidencialidad de los datos y de administrar los permisos de su equipo.' },
      { type: 'p', text: '6. Protección de datos. El usuario actúa como responsable del tratamiento de los datos de tutores y de la información clínica de los pacientes, conforme a la Ley N.° 25.326 y demás normativa aplicable. SyncVete actúa como proveedor tecnológico y encargado del tratamiento, siguiendo instrucciones del usuario. No comercializa ni usa la información clínica con fines publicitarios.' },
      { type: 'p', text: '7. Historia clínica. La historia clínica registrada en SyncVete pertenece al profesional o institución titular de la cuenta. El usuario responde por su contenido, exactitud, actualización y conservación legal.' },
      { type: 'p', text: '8. Recetas y documentos. Recetas, certificados y demás documentos emitidos con SyncVete son herramientas de apoyo. El usuario verifica el cumplimiento de la normativa vigente, incluidas recetas electrónicas u otras disposiciones aplicables.' },
      { type: 'p', text: '9. Disponibilidad. Se realizan esfuerzos razonables para mantener el servicio. Pueden ocurrir interrupciones por mantenimiento, actualizaciones, fallas técnicas, conectividad, fuerza mayor o hechos ajenos al proveedor.' },
      { type: 'p', text: '10. Período de prueba. Si hay trial, dura lo informado al registrarse. Al finalizar, algunas funciones pueden limitarse hasta contratar un plan.' },
      { type: 'p', text: '11. Planes y pagos. Los servicios pagos se rigen por los valores publicados al contratar. Salvo disposición expresa, los importes pueden actualizarse con aviso; lo abonado no se reembolsa respecto de períodos ya usados; la falta de pago puede suspender el servicio.' },
      { type: 'p', text: '12. Propiedad intelectual. Software, diseño, interfaz, logos, código, documentación, bases de datos y marcas de SyncVete son del proveedor o de sus titulares. El uso no cede esos derechos. Queda prohibida la reproducción, copia, modificación, ingeniería inversa o explotación no autorizada.' },
      { type: 'p', text: '13. Uso prohibido. No usar la plataforma para ilícitos; no acceder a otras cuentas; no alterar el sistema; no introducir malware; no hacer pruebas de intrusión sin autorización; no copiar ni distribuir el software; no usarlo para fines distintos de la gestión veterinaria.' },
      { type: 'p', text: '14. Exportación. El usuario puede pedir la exportación de su información según las funciones y condiciones comerciales vigentes. La información clínica pertenece al titular de la cuenta.' },
      { type: 'p', text: '15. Suspensión. SyncVete puede suspender una cuenta ante incumplimiento, fraude, riesgo de seguridad u obligación legal.' },
      { type: 'p', text: '16. Limitación de responsabilidad. SyncVete no garantiza resultados clínicos, diagnósticos ni tratamientos. La responsabilidad profesional frente al tutor y al paciente corresponde al veterinario o a la clínica. El proveedor no responde por interrupciones de terceros, conectividad, fuerza mayor o uso indebido.' },
      { type: 'p', text: '17. Modificaciones. Estos términos pueden actualizarse por cambios normativos, técnicos o nuevas funciones. Rige la versión publicada. El uso continuado implica aceptación.' },
      { type: 'p', text: '18. Terminación. El usuario puede pedir la baja en cualquier momento. Finalizada la relación, SyncVete puede conservar información durante los plazos legales y luego eliminarla de forma segura, salvo exportación u obligación de conservación.' },
      { type: 'p', text: '19. Ley y jurisdicción. Se rigen por las leyes de la República Argentina. Las controversias se someten a los tribunales ordinarios competentes de la República Argentina, salvo otra competencia legal.' },
      { type: 'p', text: '20. Contacto. Las consultas se canalizan por el soporte oficial publicado en la plataforma.' },
    ],
  },
  {
    slug: 'privacidad',
    title: 'Política de Privacidad',
    summary: 'Cómo SyncVete trata datos personales de usuarios, tutores y pacientes.',
    blocks: [
      { type: 'p', text: `Versión ${V} — República Argentina.` },
      { type: 'p', text: '1. Introducción. SyncVete respeta la privacidad de sus usuarios. Esta política describe cómo se recopilan, usan, almacenan y protegen los datos conforme a la Ley N.° 25.326 y demás normativa aplicable. Usar SyncVete implica aceptar esta política.' },
      { type: 'p', text: '2. Responsable. El profesional o la clínica que crea la cuenta es el responsable del tratamiento de los datos de tutores y de la información clínica de los pacientes. SyncVete actúa como encargado, solo por cuenta e instrucción del responsable.' },
      { type: 'p', text: '3. Datos del usuario. Según el uso, puede procesarse nombre, matrícula profesional, especialidad, documento, email, teléfono, domicilio profesional, facturación, usuarios y permisos.' },
      { type: 'p', text: '4. Datos de tutores y pacientes. Según lo que registre el profesional: datos identificatorios y de contacto del tutor; ficha del paciente; historia clínica; antecedentes; diagnósticos; evoluciones; medicación; estudios; imágenes; turnos; recetas; internación; vacunas; y datos administrativos de la atención.' },
      { type: 'p', text: '5. Finalidad. Administrar la clínica, turnos, historias, recetas, comunicación con tutores (incluidos WhatsApp y portal), soporte técnico, mejora del servicio y obligaciones legales. SyncVete no usa datos clínicos para publicidad, venta de información ni perfiles comerciales de tutores o pacientes.' },
      { type: 'p', text: '6. Base legal. Relación contractual, obligaciones legales del profesional o la clínica, instrucciones del responsable y consentimientos que el profesional obtenga cuando la ley lo requiera.' },
      { type: 'p', text: '7. Acceso. Solo el titular, usuarios autorizados, personal técnico de SyncVete cuando sea estrictamente necesario para soporte (con confidencialidad) y autoridades competentes por obligación legal.' },
      { type: 'p', text: '8. Compartir. SyncVete no vende datos. Solo se comparte a pedido del responsable, por obligación legal, por autoridad competente o con proveedores tecnológicos bajo confidencialidad y seguridad.' },
      { type: 'p', text: '9. Seguridad. Medidas razonables contra accesos no autorizados, alteración, pérdida, destrucción o divulgación: HTTPS, autenticación, permisos, auditoría, backups y monitoreo.' },
      { type: 'p', text: '10. Conservación. Mientras haya contrato o cuenta activa, o sea necesario por ley o requerimientos. Luego se eliminan de forma segura.' },
      { type: 'p', text: '11. Derechos. Los tutores pueden ejercer acceso, rectificación, actualización y, cuando corresponda, supresión (Ley N.° 25.326) ante el profesional o la clínica responsable. El titular de la cuenta puede acceder, actualizar, exportar y pedir la baja, sujeto a conservación legal.' },
      { type: 'p', text: '12. Proveedores. Puede usarse infraestructura, almacenamiento, correo, backups, monitoreo o autenticación de terceros con medidas compatibles.' },
      { type: 'p', text: '13. Transferencias. Si hay tratamiento fuera de Argentina, se procurará cumplir la ley y usar proveedores con seguridad adecuada.' },
      { type: 'p', text: '14. Cookies. Ver la Política de Cookies. Sirven para sesión, preferencias, experiencia y estadísticas de funcionamiento.' },
      { type: 'p', text: '15. Menores. SyncVete no está destinado a uso directo por menores. Datos de tutores menores solo los carga un profesional autorizado conforme a la ley.' },
      { type: 'p', text: '16. Modificaciones. Puede actualizarse. Rige la versión publicada.' },
      { type: 'p', text: '17. Contacto. Canales oficiales de la plataforma. Los titulares también pueden acudir a la autoridad de control argentina.' },
    ],
  },
  {
    slug: 'seguridad',
    title: 'Política de Seguridad de la Información',
    summary: 'Medidas técnicas y organizativas para proteger la información de la clínica.',
    blocks: [
      { type: 'p', text: `Versión ${V} — República Argentina.` },
      { type: 'p', text: '1. Objetivo. Esta política describe las medidas de SyncVete para proteger confidencialidad, integridad, disponibilidad y trazabilidad, y reducir accesos no autorizados, pérdida, alteración o divulgación de datos personales y clínicos.' },
      { type: 'p', text: '2. Alcance. Aplica a veterinarios, clínicas, personal administrativo, usuarios autorizados y personal técnico de SyncVete cuando haga falta para soporte.' },
      { type: 'p', text: '3. Principios. Confidencialidad, integridad, disponibilidad, trazabilidad, acceso por permisos, mínimo privilegio y mejora continua.' },
      { type: 'p', text: '4. Protección. HTTPS/TLS, autenticación, almacenamiento protegido, separación lógica entre clínicas (multi-tenant con RLS), permisos por usuario, auditoría, backups periódicos, monitoreo y actualizaciones de seguridad.' },
      { type: 'p', text: '5. Usuarios. Cada cuenta es individual e intransferible. El titular asigna solo los permisos necesarios, da de baja a quien deja el equipo, revisa accesos y no comparte contraseñas. SyncVete puede suspender cuentas ante riesgo.' },
      { type: 'p', text: '6. Contraseñas. El usuario guarda sus credenciales. Se recomiendan contraseñas robustas (mayúsculas, minúsculas, números y caracteres especiales) y no reutilizarlas.' },
      { type: 'p', text: '7. Control de acceso. El acceso se limita según el rol (propietario, administrador, veterinario, enfermero/a, recepcionista, cajero/a, laboratorio, solo lectura u otros perfiles). Cada usuario ve lo necesario para su función.' },
      { type: 'p', text: '8. Auditoría. Pueden registrarse inicios de sesión, accesos a historias, modificaciones, recetas, turnos, configuración y altas/bajas de usuarios, para seguridad, soporte, prevención de fraude y cumplimiento.' },
      { type: 'p', text: '9. Backups. Copias periódicas para reducir pérdida de información, protegidas y usadas para recuperación. Frecuencia y retención pueden ajustarse.' },
      { type: 'p', text: '10. Disponibilidad. Esfuerzos razonables de alta disponibilidad. Puede haber cortes por mantenimiento (avisado cuando sea posible), actualizaciones, infraestructura, terceros, incidentes o fuerza mayor.' },
      { type: 'p', text: '11. Incidentes. SyncVete puede contener, investigar, restaurar, preservar evidencias y corregir. Si el incidente afecta de forma significativa los datos, se informa al titular en un plazo razonable.' },
      { type: 'p', text: '12. Dispositivos. El usuario protege sus equipos: sistema actualizado, antivirus cuando corresponda, bloqueo al ausentarse, evitar equipos públicos y cerrar sesión.' },
      { type: 'p', text: '13. Uso aceptable. Prohibido compartir usuarios, acceder a cuentas ajenas, modificar sin autorización, hacer tests de intrusión, introducir malware, usos ilícitos o interferir el servicio.' },
      { type: 'p', text: '14. Conservación de logs. El tiempo necesario para seguridad, incidentes, ley y requerimientos.' },
      { type: 'p', text: '15. Responsabilidades. El usuario protege credenciales, respeta permisos, informa incidentes y cumple la ley. SyncVete implementa medidas razonables, mantiene la infraestructura, corrige vulnerabilidades cuando es posible y actúa como encargado.' },
      { type: 'p', text: '16. Limitaciones. Ningún sistema garantiza seguridad absoluta. SyncVete no garantiza la inexistencia de incidentes por ataques, terceros, Internet, fuerza mayor o causas fuera de su control razonable.' },
      { type: 'p', text: '17–18. Actualizaciones y contacto. Rige la versión publicada. Informar de inmediato cualquier sospecha de acceso no autorizado.' },
    ],
  },
  {
    slug: 'aviso-legal',
    title: 'Aviso Legal',
    summary: 'Acceso, navegación y naturaleza del servicio.',
    blocks: [
      { type: 'p', text: `Versión ${V} — República Argentina.` },
      { type: 'p', text: '1. Objeto. Este aviso regula el acceso y uso de SyncVete. Usar la plataforma implica aceptar este aviso, los Términos, la Privacidad, la Seguridad y los demás documentos legales publicados.' },
      { type: 'p', text: '2. Naturaleza. SyncVete es software de gestión para clínicas veterinarias. No presta servicios veterinarios, no diagnostica, no prescribe y no reemplaza el criterio profesional. Toda decisión clínica es del veterinario responsable.' },
      { type: 'p', text: '3. Uso autorizado. Conforme a la ley, de buena fe, respetando derechos de terceros y solo para gestión clínica y administrativa veterinaria. Queda prohibido el uso ilícito o que afecte el funcionamiento.' },
      { type: 'p', text: '4. Propiedad intelectual. Software, código, diseño, interfaz, logos, marcas, documentación, bases propias y contenido original pertenecen al proveedor o a sus titulares. El uso no cede esos derechos.' },
      { type: 'p', text: '5. Licencia. Limitada, personal, revocable, no exclusiva e intransferible, vigente el contrato y según los Términos. El usuario no adquiere propiedad sobre el software.' },
      { type: 'p', text: '6. Restricciones. Prohibido copiar, modificar, descompilar, hacer ingeniería inversa, distribuir versiones modificadas, vender o sublicenciar, quitar avisos de PI o vulnerar la seguridad, salvo autorización o mandato legal.' },
      { type: 'p', text: '7. Exactitud. Se procura el correcto funcionamiento. El usuario verifica la información que carga.' },
      { type: 'p', text: '8. Enlaces y terceros. SyncVete no controla sitios o servicios de terceros a los que se pueda acceder.' },
      { type: 'p', text: '9. Responsabilidad. El proveedor no responde por decisiones clínicas ni por el contenido ingresado por usuarios.' },
      { type: 'p', text: '10. Ley aplicable. República Argentina.' },
    ],
  },
  {
    slug: 'dpa',
    title: 'Acuerdo de Tratamiento de Datos (DPA)',
    summary: 'SyncVete como encargado del tratamiento por cuenta de la clínica.',
    blocks: [
      { type: 'p', text: `Versión ${V} — República Argentina.` },
      { type: 'p', text: '1. Objeto. Este DPA regula el tratamiento de datos personales que SyncVete realiza como encargado, por cuenta e instrucción del profesional o clínica. Complementa los Términos y la Privacidad.' },
      { type: 'p', text: '2. Partes. Responsable: titular de la cuenta. Encargado: SyncVete, proveedor de la plataforma.' },
      { type: 'p', text: '3. Tratamiento. Solo para prestar el servicio: pacientes y tutores, agenda, historia clínica, recetas, turnos, archivos, reportes, WhatsApp, portal y demás funciones contratadas.' },
      { type: 'p', text: '4. Categorías. Identificatorios, contacto, laborales, administrativos, datos de salud animal, diagnósticos, tratamientos, antecedentes, recetas, imágenes, estudios y adjuntos.' },
      { type: 'p', text: '5. Titulares. Tutores, profesionales, personal administrativo y usuarios autorizados.' },
      { type: 'p', text: '6. Obligaciones de SyncVete. Seguir instrucciones; no usar los datos para fines propios; no venderlos; confidencialidad; seguridad razonable; acceso limitado; colaborar con el responsable; permitir exportación razonable.' },
      { type: 'p', text: '7. Obligaciones del responsable. Consentimientos, licitud, Ley N.° 25.326 y normativa aplicable, exactitud, permisos y atención de solicitudes de titulares.' },
      { type: 'p', text: '8–9. Confidencialidad y seguridad. Quien trate datos por SyncVete queda obligado a confidencialidad, incluso después del contrato. Medidas: autenticación, cifrado, accesos, auditoría, separación lógica, backups y monitoreo.' },
      { type: 'p', text: '10. Subencargados. Puede haber infraestructura, almacenamiento, autenticación, correo, monitoreo o respaldo de terceros con seguridad compatible.' },
      { type: 'p', text: '11. Transferencias internacionales. Con proveedores adecuados y respeto de la normativa.' },
      { type: 'p', text: '12. Incidentes. Contener, investigar, restaurar e informar al responsable cuando corresponda.' },
      { type: 'p', text: '13. Derechos. El responsable atiende acceso, rectificación, actualización y supresión. SyncVete colabora cuando sea técnicamente posible.' },
      { type: 'p', text: '14–15. Conservación y fin de servicio. Mientras haga falta para el servicio o la ley. Al terminar: eliminar, anonimizar o conservar solo lo exigido, previa exportación si se pide.' },
      { type: 'p', text: '16. Auditoría. El responsable puede pedir información general sobre medidas, sin comprometer a otros clientes.' },
      { type: 'p', text: '17–20. Cada parte responde por sus obligaciones. El responsable responde por la legitimidad de lo cargado. SyncVete, por el tratamiento según instrucciones. Vigencia mientras haya cuenta o se traten datos. Modificaciones publicadas. Ley y tribunales de la República Argentina.' },
    ],
  },
  {
    slug: 'cookies',
    title: 'Política de Cookies',
    summary: 'Cookies y almacenamiento local usados por SyncVete.',
    blocks: [
      { type: 'p', text: `Versión ${V} — República Argentina.` },
      { type: 'p', text: '1. Objeto. Explica cómo SyncVete usa cookies y tecnologías similares para el funcionamiento, la experiencia y la seguridad. Seguir usando el sitio implica aceptarlas, salvo que las deshabilite el navegador cuando sea posible.' },
      { type: 'p', text: '2. Qué son. Archivos de texto en el navegador o dispositivo. No ejecutan programas ni contienen virus.' },
      { type: 'p', text: '3. Tipos. Esenciales: sesión, autenticación, seguridad y configuración básica (no se pueden apagar sin romper el servicio). Preferencias: idioma, tema claro/oscuro, color de acento. Análisis: páginas, tiempos, errores y rendimiento, sin identificar al usuario. Seguridad: detectar actividad sospechosa y proteger cuentas.' },
      { type: 'p', text: '4. Tecnologías similares. Local Storage y Session Storage (por ejemplo el tema) e identificadores de sesión.' },
      { type: 'p', text: '5. Terceros. Autenticación, análisis, monitoreo o protección pueden usar cookies de proveedores (p. ej. infraestructura de autenticación).' },
      { type: 'p', text: '6. Gestión. El navegador permite bloquear o borrar cookies; ello puede impedir iniciar sesión. Preferencias de tema se guardan en este dispositivo.' },
      { type: 'p', text: '7. Actualizaciones. Rige la versión publicada en la plataforma.' },
    ],
  },
  {
    slug: 'backups',
    title: 'Política de Backups y Recuperación',
    summary: 'Copias de seguridad y continuidad del servicio.',
    blocks: [
      { type: 'p', text: `Versión ${V} — República Argentina.` },
      { type: 'p', text: '1. Objetivo. Lineamientos para copias de seguridad, recuperación y continuidad, a fin de reducir la pérdida de datos ante incidentes, errores o eventos imprevistos.' },
      { type: 'p', text: '2. Alcance. Historias clínicas, fichas, agenda, recetas, imágenes, documentación, datos administrativos, configuración y auditoría.' },
      { type: 'p', text: '3. Copias. Periódicas de información crítica: bases de datos, archivos de usuarios, configuraciones y registros necesarios para recuperar el servicio.' },
      { type: 'p', text: '4. Protección. Medidas contra accesos no autorizados, alteraciones, pérdidas, destrucción o divulgación. Cifrado y control de acceso cuando sea posible.' },
      { type: 'p', text: '5. Frecuencia. Según operación, volumen, infraestructura, plan y criterio técnico. Puede cambiar para mejorar seguridad o continuidad.' },
      { type: 'p', text: '6–7. Recuperación. Esfuerzos razonables según el incidente, la infraestructura y los respaldos disponibles. Los objetivos de recuperación (RPO/RTO) son operativos y pueden variar; no constituyen un compromiso de tiempo fijo salvo que un plan lo indique.' },
      { type: 'p', text: '8. Responsabilidad del usuario. Exportar y conservar copias propias cuando la normativa o su operación lo exijan.' },
      { type: 'p', text: '9. Limitaciones. Un backup no garantiza recuperación total ante corrupción previa, borrados del usuario, fuerza mayor o fallas de terceros.' },
    ],
  },
  {
    slug: 'licencias',
    title: 'Licencias de Software y Propiedad Intelectual',
    summary: 'Titularidad del software y licencia de uso.',
    blocks: [
      { type: 'p', text: `Versión ${V} — República Argentina.` },
      { type: 'p', text: '1. Objeto. Derechos de PI y condiciones de uso del software SyncVete. Complementa los Términos.' },
      { type: 'p', text: '2. Titularidad. Software, código, arquitectura, diseño, interfaz, logos, documentación, bases propias, marca y contenido original son del titular o licenciantes. Lo no concedido queda reservado.' },
      { type: 'p', text: '3. Licencia. Limitada, personal, revocable, no exclusiva, intransferible y no sublicenciable, según el plan y mientras dure el contrato. No transfiere la propiedad.' },
      { type: 'p', text: '4. Usos permitidos. Administrar la clínica, pacientes, historias, documentación veterinaria, turnos y funciones del plan.' },
      { type: 'p', text: '5. Prohibido. Copiar, reproducir, modificar, distribuir, vender, alquilar, sublicenciar, descompilar, ingeniería inversa, quitar avisos de PI, derivar productos o usar SyncVete para competir con el proveedor, sin autorización.' },
      { type: 'p', text: '6. Terceros. Componentes de código abierto u otras librerías conservan su licencia. Se pondrá a disposición la información exigida por esas licencias.' },
      { type: 'p', text: '7. Marcas. “SyncVete”, el logotipo y signos distintivos no pueden usarse sin autorización escrita.' },
      { type: 'p', text: '8. Datos. Lo cargado por la clínica sigue siendo de la clínica. El software sigue siendo del proveedor.' },
    ],
  },
  {
    slug: 'historia-clinica',
    title: 'Aviso sobre Historia Clínica y Recetas',
    summary: 'Alcance de la historia clínica, recetas y documentos veterinarios.',
    blocks: [
      { type: 'p', text: `Versión ${V} — República Argentina.` },
      { type: 'p', text: '1. Objeto. Condiciones de historias clínicas, recetas, certificados y documentación sanitaria generada en SyncVete.' },
      { type: 'p', text: '2. Apoyo profesional. No reemplaza el criterio veterinario ni la relación con el tutor. Diagnóstico, terapéutica y administración corresponden al profesional tratante.' },
      { type: 'p', text: '3. Historia clínica. Es un registro elaborado por el profesional o la clínica. SyncVete no modifica, interpreta, valida ni controla lo ingresado.' },
      { type: 'p', text: '4. Exactitud. El profesional verifica que sea completa, exacta, actualizada, legible y conforme a la normativa. Las correcciones son su responsabilidad.' },
      { type: 'p', text: '5. Conservación. El profesional o la clínica cumple los plazos legales. SyncVete almacena y administra; no sustituye esas obligaciones.' },
      { type: 'p', text: '6. Recetas. Se generan con lo que carga el profesional, quien verifica identidad del paciente, medicación, dosis, frecuencia, duración y la ley aplicable.' },
      { type: 'p', text: '7. Receta electrónica. Si se ofrece, queda sujeta a la normativa e integraciones vigentes. Si una función no está homologada con sistemas oficiales, el documento tiene solo el alcance que indique la plataforma.' },
      { type: 'p', text: '8. Certificados. Constancias, órdenes e informes se emiten bajo responsabilidad del profesional. SyncVete no garantiza validez jurídica que dependa de organismos externos.' },
      { type: 'p', text: '9. Firma. Firmas electrónicas o digitales, cuando existan, deben ajustarse a la ley. El profesional usa mecanismos autorizados si la norma lo exige.' },
      { type: 'p', text: '10. Identificación. Nombre, matrícula, fecha y demás requisitos legales del emisor son responsabilidad del profesional.' },
    ],
  },
  {
    slug: 'consentimiento',
    title: 'Consentimiento del Profesional',
    summary: 'Declaraciones al crear una cuenta en SyncVete.',
    blocks: [
      { type: 'p', text: `Versión ${V} — República Argentina.` },
      { type: 'p', text: 'Al crear una cuenta, el profesional o la clínica declara haber leído y aceptar los Términos, la Privacidad, la Seguridad y el DPA, y además:' },
      { type: 'p', text: '1. Actúa como responsable del tratamiento de datos de tutores y de la información clínica, conforme a la Ley N.° 25.326 y normativa aplicable. SyncVete es proveedor tecnológico y encargado, siguiendo sus instrucciones.' },
      { type: 'p', text: '2. La información se obtiene y trata conforme a la ley y, cuando corresponda, con consentimiento del tutor u otra base legal.' },
      { type: 'p', text: '3. Se compromete a ingresar datos completos, veraces y actualizados.' },
      { type: 'p', text: '4. Preserva la confidencialidad y limita el acceso a personas autorizadas.' },
      { type: 'p', text: '5. Crea solo usuarios autorizados, asigna permisos, desactiva accesos de quien deje el equipo y protege credenciales.' },
      { type: 'p', text: '6. Usa SyncVete solo con fines profesionales de atención veterinaria y administración de la clínica.' },
      { type: 'p', text: '7–8. Es responsable del contenido y conservación de historias clínicas y de recetas y documentos que emita.' },
      { type: 'p', text: '9. Usa contraseñas seguras, protege dispositivos, cierra sesión e informa incidentes.' },
      { type: 'p', text: '10. Comprende que puede haber interrupciones por mantenimiento, fallas o causas ajenas.' },
      { type: 'p', text: '11. La información clínica es de la clínica; el software es de SyncVete.' },
      { type: 'p', text: '12. Acepta comunicaciones de funcionamiento, actualizaciones, cambios legales, mantenimiento, seguridad, facturación y soporte.' },
      { type: 'p', text: '13. Declara que los datos de registro son correctos y que tiene capacidad para contratar.' },
    ],
  },
];

export function getLegalDoc(slug: string) {
  return LEGAL_DOCS.find((doc) => doc.slug === slug) ?? null;
}
